export const checkUser ='checkUser';
export const logOut = 'logOut';
export const showLoading = 'showLoading';
export const hideLoading = 'hideLoading';
export const showAlert = 'showAlert';
export const changeVisibility = 'changeVisibility';
export const fetchData = 'fetchData';
export const editSchedule = 'editSchedule';
export const chooseCell = 'chooseCell';